language: node_js
node_js:
  - "14.17.0"
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: firebase
  token:
    secure: "1//0hDuV3q1eYiTuCgYIARAAGBESNwF-L9IrxDOh2VHXo0lnX504STf5cLPBrsDJjbKnJBNZj56WCvNhNgkcy--zzGCkmRPHLF5hA4o"
  on:
    branch: main