language: node_js
node_js:
  - "14.17.0"
before_script:
  - export CI=false
  - yarn add -D firebase-tools
  - yarn build
cache:
  yarn: true
  directories:
    - node_modules
script:
  - firebase deploy --only hosting --token "1//0hDuV3q1eYiTuCgYIARAAGBESNwF-L9IrxDOh2VHXo0lnX504STf5cLPBrsDJjbKnJBNZj56WCvNhNgkcy--zzGCkmRPHLF5hA4o"