language: node_js
node_js:
  - "v14.17"
cache:
  directories:
    - node_modules
jobs:
  include:
  - stage: test
    script:
    - yarn install
    - yarn build
  - stage: deploy
    if: branch = main
    script: firebase deploy